name: Deploy to Github Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.merged == true }}
    steps:
      - uses: actions/checkout@latest
      - uses: pnpm/action-setup@latest
        with:
          version: latest
          run_install: false
      - uses: actions/setup-node@vlatest
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm i
      - run: pnpm build
      - uses: actions/configure-pages@latest
      - uses: actions/upload-pages-artifact@latest
        with:
          path: "./docs"
      - id: deployment
        uses: actions/deploy-pages@latest
